import { Moon, Sun } from "lucide-react";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useTheme, type Theme } from "@/hooks/useTheme";

const FAQS: { q: string; a: string }[] = [
  {
    q: "Where do the drafts come from?",
    a: "Each draft is generated by an AI model from the details you type into the form. Nothing is invented from outside sources, so always add the facts you want included.",
  },
  {
    q: "Can I edit a draft after it is generated?",
    a: "Yes. The output panel is fully editable — change any wording, then copy it or export it as a .txt file.",
  },
  {
    q: "Are my drafts saved?",
    a: "Your recent drafts stay in the session history on this device while you are signed in. They are cleared when you close the app.",
  },
  {
    q: "How accurate are meeting notes and research briefs?",
    a: "They summarise only what you paste in. Always review action items, names and figures before sharing them.",
  },
  {
    q: "How do I switch back to a light or dark look?",
    a: "Open Settings, go to Appearance and pick Light or Dark. Your choice is remembered on this device.",
  },
];

export function SettingsDialog({
  open,
  onOpenChange,
  defaultTab = "appearance",
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  defaultTab?: "appearance" | "about" | "faqs";
}) {
  const { theme, setTheme } = useTheme();

  const options: { value: Theme; label: string; icon: typeof Sun }[] = [
    { value: "light", label: "Light", icon: Sun },
    { value: "dark", label: "Dark", icon: Moon },
  ];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Settings</DialogTitle>
          <DialogDescription>
            Choose how the workspace looks and learn how it works.
          </DialogDescription>
        </DialogHeader>

        <Tabs defaultValue={defaultTab} className="w-full">
          <TabsList className="w-full">
            <TabsTrigger value="appearance" className="flex-1">
              Appearance
            </TabsTrigger>
            <TabsTrigger value="about" className="flex-1">
              About
            </TabsTrigger>
            <TabsTrigger value="faqs" className="flex-1">
              FAQs
            </TabsTrigger>
          </TabsList>

          <TabsContent value="appearance" className="mt-4">
            <p className="text-sm text-muted-foreground">
              Pick a theme for this device.
            </p>
            <div className="mt-3 grid grid-cols-2 gap-3">
              {options.map((o) => (
                <button
                  key={o.value}
                  type="button"
                  onClick={() => setTheme(o.value)}
                  aria-pressed={theme === o.value}
                  className={cn(
                    "flex items-center gap-3 rounded-xl border border-border bg-card p-4 text-left text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground",
                    theme === o.value && "border-primary ring-2 ring-ring/40",
                  )}
                >
                  <o.icon className="size-4 text-primary" />
                  {o.label}
                </button>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="about" className="mt-4 space-y-3 text-sm">
            <p className="font-medium">Workplace AI · version 1.0</p>
            <p className="text-muted-foreground">
              An AI productivity workspace with three assistants: a professional email
              writer, a meeting-notes summariser that pulls out action items, and a
              research brief builder. Every result is editable before you copy or export
              it.
            </p>
            <p className="text-muted-foreground">
              Drafts are suggestions, not final decisions. Review names, dates, figures
              and commitments before sending anything to colleagues or clients.
            </p>
          </TabsContent>

          <TabsContent value="faqs" className="mt-4">
            <Accordion type="single" collapsible className="w-full">
              {FAQS.map((f, i) => (
                <AccordionItem key={i} value={`faq-${i}`}>
                  <AccordionTrigger className="text-left text-sm">{f.q}</AccordionTrigger>
                  <AccordionContent className="text-sm text-muted-foreground">
                    {f.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </TabsContent>
        </Tabs>

        <div className="flex justify-end">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Done
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
